### ISSUE TITLE
Problems in yacl/math/mpint

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#107]
（1）It seems that libtommath is keen on 64 bit platforms, defining MP_64BIT. But it may define MP_32BIT. So mp_digit is likely uint64_t. It is possible that mp_digit is uint32_t. MP_DIGIT_BIT may be 60, 31, 28 respectively.
	In math/mpint/mp_int.cc,
	
	template <>
	void MPInt::Set(int64_t value) {
	  MPINT_ENFORCE_OK(mp_grow(&n_, 2));
	  mp_set_i64(&n_, value);
	}
	
	…
	
	template <>
	void MPInt::Set(uint128_t value) {
	  MPINT_ENFORCE_OK(mp_grow(&n_, 3));
	  mp_set_u128(&n_, value);
	}
	

	Should we judge whether the platform is 64 bit or 32 bit before we use mp_grow(&n_,int )? To be exact, judge the value of MP_DIGIT_BIT.

	(2) Maybe the annotation has some errors.

	* > RandomExactBits
	*     - Generate an exact bit_size random number, the smb is not guaranteed
	
	Should “smb” be “msb”?

  In the annotation of SlowCustomPow, we usually write “base ** scalar” instead of “scalar ** base” as far as I know.

**Comment by anakinxc** [comment]
For question 1: no, we do not support 32bit platforms.

@Jamie-Cui can you take a look at question 2?

**Comment by Jamie-Cui** [comment]
> Should “smb” be “msb”?

Yes, it's a typo

**Comment by maths644311798** [comment]
OK. I have proposed a PR.

**Comment by maths644311798** [comment]
@Jamie-Cui , there are more problems now.

(3) In tommath_ext_features,

	// Pocklington's criterion:
	// Let P>1 be an integer, and suppose there exist natural numbers A and Q such
	// that
	//   * A^{P-1} = 1 mod P
	//   * Q is prime, Q|N−1 and Q > sqrt(P) - 1
	//   * gcd(A^{(P-1)/Q} - 1, P) = 1
// Then P is prime

“Q|N-1” should be “Q|P-1”.

(4)	In tommath_ext_features, note that qsize = psize – 1.
So for the initial q, the number of bits used by p=2q+1 is equal to psize.
The following code is not good

void mp_ext_safe_prime_rand(mp_int *p, int t, int psize)
{
…
 do{
…
  for(…){

	if (mp_ext_count_bits_fast(*p) != psize) {
	        continue;
      }
}
}
}

because q is going to be bigger in the for cycle and so is p. mp_ext_count_bits_fast(*p) != psize means mp_ext_count_bits_fast(*p) > psize. And it will never equal psize. Maybe we can just break the for cycle at this case and check (mp_ext_count_bits_fast(*p) != psize) outside of the for cycle.

Moreover, in the do cycle, 

	if (!is_pocklington_criterion_satisfied(&q)) {
	      continue;
    }

I think we should check is_pocklington_criterion_satisfied(&p) rather than q.

**Comment by anakinxc** [comment]
> @Jamie-Cui , there are more problems now.
> 
> (3) In tommath_ext_features,
> 
> ```
> // Pocklington's criterion:
> // Let P>1 be an integer, and suppose there exist natural numbers A and Q such
> // that
> //   * A^{P-1} = 1 mod P
> //   * Q is prime, Q|N−1 and Q > sqrt(P) - 1
> //   * gcd(A^{(P-1)/Q} - 1, P) = 1
> ```
> 
> // Then P is prime
> 
> “Q|N-1” should be “Q|P-1”.
> 
> (4) In tommath_ext_features, note that qsize = psize – 1. So for the initial q, the number of bits used by p=2q+1 is equal to psize. The following code is not good
> 
> void mp_ext_safe_prime_rand(mp_int *p, int t, int psize) { … do{ … for(…){
> 
> ```
> if (mp_ext_count_bits_fast(*p) != psize) {
>         continue;
>   }
> ```
> 
> } } }
> 
> because q is going to be bigger in the for cycle and so is p. mp_ext_count_bits_fast(*p) != psize means mp_ext_count_bits_fast(*p) > psize. And it will never equal psize. Maybe we can just break the for cycle at this case and check (mp_ext_count_bits_fast(*p) != psize) outside of the for cycle.
> 
> Moreover, in the do cycle,
> 
> ```
> if (!is_pocklington_criterion_satisfied(&q)) {
>       continue;
> }
> ```
> 
> I think we should check is_pocklington_criterion_satisfied(&p) rather than q.

@usafchn can you take a look at these two questions?

**Comment by maths644311798** [comment]
(3) and (4) are unsolved. But let me add one more question.
(5)	In tommath_ext_features, void mp_ext_set_bit(mp_int *a, int index, uint8_t value), there is a for cycle

	for (int i = a->used + 1; i <= limb; ++i) {
	      a->dp[i] = 0;
    }

This for cycle is somewhat redundant because mp_grow() has already reset the digits after a->dp[a->alloc] inclusive. So the for cycle should be

	for (int i = a->used; i < a->alloc; ++i) {
	      a->dp[i] = 0;
    }

Or if the allocated digits are forced to be zero, we can delete the for cycle.

**Comment by zheyang0825** [comment]
（3) yes，it‘s a typo.
  (4) yes,  `mp_ext_count_bits_fast(*p) != psize` should be checked outside the for cycle, and the `p`  other than `q` should be test in `is_pocklington_criterion_satisfied`
