### ISSUE TITLE
sm4Drbg Reseed 

### ISSUE THREAD

**Issue by PrimumMobile** [secretflow/yacl#123]
sm4Drbg Generate函数在执行Reseed之前获取了一次entropy_input_ ，
https://github.com/secretflow/yacl/blob/main/yacl/crypto/base/drbg/sm4_drbg.cc#L247

而后在Reseed函数内部又重新获取了一次entropy_input_ ，
https://github.com/secretflow/yacl/blob/main/yacl/crypto/base/drbg/sm4_drbg.cc#L214

247行获取entropy_input_是否可以删除？

**Comment by zhanglei486** [comment]
247行获取entropy_input_应该是可以去掉的，谢谢提醒
如果感兴趣可以给我们提修改的PR
