### ISSUE TITLE
The order of headers

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#129]
The order of headers in /yacl/link/transport/interconnection_base.cc is not good.

#include "yacl/link/transport/interconnection_base.h"

will actually include "spdlog/spdlog.h". But 

#include "fmt/ostream.h"

should be above "spdlog/spdlog.h". See also https://github.com/gabime/spdlog/issues/2872#issue-1874742851

**Comment by anakinxc** [comment]
This is a bug in fmt/spdlog, not yacl.
