### ISSUE TITLE
Problems in brpc_blackbox_link

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#131]
In brpc_blackbox_link.cc line 197,

`options.max_retry = options.max_retry;`

I guess the right-hand-side should be options_. max_retry.

Moreover, in the function

`brpc::ChannelOptions BrpcBlackBoxLink::GetChannelOption(const SSLOptions* ssl_opts)`
...
`auto retry_policy = std::make_unique<BlackboxRetryPolicy>(
      options_.retry_interval_ms, options_.aggressive_retry, push_wait_ms_);`
...
`retry_policy_ = std::move(retry_policy);`

Why does yacl set the value of retry_policy_ in GetChannelOption? What's the relationship between retry_policy_ and GetChannelOption?

**Comment by huocun-ant** [comment]
Yes, it should be `options_. max_retry`.
In brpc, `retry_policy` is part of channel option, so retry_policy_ is set in GetChannelOption.
