### ISSUE TITLE
能否实现按顺序实现多次recv与sendaynsc

### ISSUE THREAD

**Issue by yongzhao-yan-postgraduate** [secretflow/yacl#133]
yacl/link/transport/channel能否实现多次发送与接受

**Comment by maths644311798** [comment]
可以多次发送与接受。Channel类的成员变量就是专门为了多次收发设计的。比如msg_db_

// msg_key -> <value, seq_id>
  std::map<std::string, std::pair<Buffer, size_t>> msg_db_;
