### ISSUE TITLE
sm4_drbg的一些问题

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#139]
(1) 在sm4_drbg中看到《软件随机数设计指南》- 征求意见稿，请问这个文件在哪里下载？
(2) sm4_drbg为什么可以不用Nonce？
(3) 在sm4_drbg的函数Sm4Drbg::Instantiate有一句std::memset(v_.data(), 0, key_.size());，虽然目前v_和key_是一样长，但是这样看起来写不太妥，可以考虑改成

std::memset(v_.data(), 0, v_.size())；

**Comment by zhanglei486** [comment]
1. GM/T 0105-2021 软件随机数发生器设计指南，目前已经是国密行标
2. 实现还是基于2020年的征求意见稿版本，该版本中Instantiate函数没有Nonce参数，在目前的GM/T 0105中已经有Nonce了，后续会对代码进行标准符合性改进。
3. 很好的建议，可以提个PR进行修改

**Comment by maths644311798** [comment]
已提交PR。我粗略浏览了一下，目前yacl的sm4_drbg实现与GM/T 0105-2021有多处不同，除了Nonce外还有多处不同。后续如果要和这个标准一致，修改的地方挺多的。

**Comment by Jamie-Cui** [comment]
[PR](https://github.com/secretflow/yacl/pull/140) merged
