### ISSUE TITLE
The comment in ecc_spi.h

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#141]
There are comments in ecc_spi.h as below:

  // The h, cofactor.
  // Cofactor is the number of non-overlapping subgroups of points, which
  // together hold all curve points
  virtual MPInt GetCofactor() const = 0;

Some websites also make similar mistakes of calling the non-overlapping subsets "subgroups". But the exact definition of "cofactor" is the number of cosets. 
Equivalently, cofactor is the number of non-overlapping subsets of points. Of course, the subsets are divided according to a designated subgroup.

The definition can be checked in "Standards for Efficient Cryptography" and many books about elliptic curves.

**Comment by usafchn** [comment]
这个我觉得没什么问题，都行，coset 是比较学术化的表达，non-overlapping subgroups 是口语化的表达，比较直观。其实 cosets are copies of a subgroup，两者在数值上等价。要不您直接发起 PR 把注释改一下？
