### ISSUE TITLE
为什么把context的析构工作交给上层？

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#145]
首先context使用默认析构函数，那么析构的关键在于Channel的析构。Channel的析构函数如下，

~Channel() override {
    if (!send_thread_stopped_.load()) {
      SPDLOG_WARN(
          "Channel destructor is called before WaitLinkTaskFinish, try "
          "stop send thread");
      try {
        WaitAsyncSendToFinish();
      } catch (const std::exception& e) {
        SPDLOG_ERROR("Stop send thread err {}", e.what());
        if (exit_if_async_error_) {
          exit(-1);
        }
      }
    }
  }

为什么Channel析构时不直接调用WaitLinkTaskFinish()？或者Context在析构时调用WaitLinkTaskFinish()?按照目前的用法，Context析构前还要调用WaitLinkTaskFinish()，逻辑上感觉有些冗余。

**Comment by warriorpaw** [comment]
WaitLinkTaskFinish 首先不是做析构工作的，它是context这一层抽象的结束，类似ConnectToMesh是context这一层的开始。


其次WaitLinkTaskFinish是带MPI语意的接口，需要多方个参与方同步的调用这个接口，会产生通讯和顺序依赖。
放在析构函数里存在两个问题：1、析构调用顺序是语言/编译器/运行时共同决定的，c++还好，pybind到python后，什么时候构函会被调用以什么顺序调用都是不确定的；2、同一个进程内有多个context的话，靠析构的话，对WaitLinkTaskFinish的调用会被串行化，它们之间互相依赖就死锁了。
