### ISSUE TITLE
YACL ECC 模块支持 FourQ 曲线

### ISSUE THREAD

**Issue by Candicepan** [secretflow/yacl#158]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- **任务名称**：YACL 支持 FourQ 曲线
- **技术方向**：ECC 椭圆曲线密码学
- **任务难度**：热身🌟
- - **任务期望时间**：2-3 周

## 详细要求
YACL ECC 模块位于 [yacl/crypto/base/ecc](https://github.com/secretflow/yacl/blob/main/yacl/crypto/base/ecc/ecc_spi.h) 路径下, ecc_spi.h 是模块的总入口，所有椭圆曲线遵循相同的接口。目前 ECC 模块已经实现了大部分主流曲线，但是缺少 fourq，本任务需要在 ECC 模块中集成/实现 fourq 曲线。
关于 fourq 曲线更详细的介绍可参考此 paper https://eprint.iacr.org/2015/565.pdf
鉴于微软已经实现了 [FourQlib](https://github.com/microsoft/FourQlib)，简单起见您可以直接集成此 Lib 到 YACL

## 能力要求
- 精通 C++ 语言
- 了解基本 git 操作
- 了解椭圆曲线密码学（ECC）

## 操作说明
- 请在 [YACL ECC 模块](https://github.com/secretflow/yacl/blob/main/yacl/crypto/base/ecc/) 中新建一个文件夹存放您的代码
- 集成方式可参考 ECC 下其它 Lib 的集成方法，一般由一个 xxxGroup 实现曲线主体功能；一个 factory 用于创建曲线实例；一个 test 类用于单测
- 集成完成后请执行 `bazel run -c opt //yacl/crypto/base/ecc/benchmark:benchmark -- --curve=ed25519` 运行性能测试

**Comment by Tonytan123** [comment]
【tonytan233 Give it to me】

**Comment by Tonytan123** [comment]
yacl项目引入微软的fourq库，但是当前的fourq库只有git仓（https://github.com/microsoft/FourQlib），有看到yacl项目引入三方库如下所示：
def _com_github_libsodium():
    maybe(
        http_archive,
        name = "com_github_libsodium",
        type = "tar.gz",
        strip_prefix = "libsodium-1.0.18",
        sha256 = "6f504490b342a4f8a4c4a02fc9b866cbef8622d5df4e5452b46be121e46636c1",
        build_file = "@yacl//bazel:libsodium.BUILD",
        urls = [
            "https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz",
        ],
    )
引入的三方库都有完整的tar.gz文件可以下载，但是微软的fourq仓库只有git仓，这该怎么引入？

**Comment by usafchn** [comment]
@Tonytan123 可以用 [new_git_repository](https://bazel.build/rules/lib/repo/git?hl=zh-cn#new_git_repository) 函数

[例子](https://github.com/google/heir/blob/74a53e9658a06f550ace70b644c6df97ed62264b/WORKSPACE#L215)

**Comment by anakinxc** [comment]
> yacl项目引入微软的fourq库，但是当前的fourq库只有git仓（[https://github.com/microsoft/FourQlib），有看到yacl项目引入三方库如下所示：](https://github.com/microsoft/FourQlib%EF%BC%89%EF%BC%8C%E6%9C%89%E7%9C%8B%E5%88%B0yacl%E9%A1%B9%E7%9B%AE%E5%BC%95%E5%85%A5%E4%B8%89%E6%96%B9%E5%BA%93%E5%A6%82%E4%B8%8B%E6%89%80%E7%A4%BA%EF%BC%9A) def _com_github_libsodium(): maybe( http_archive, name = "com_github_libsodium", type = "tar.gz", strip_prefix = "libsodium-1.0.18", sha256 = "6f504490b342a4f8a4c4a02fc9b866cbef8622d5df4e5452b46be121e46636c1", build_file = "@yacl//bazel:libsodium.BUILD", urls = [ "https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz", ], ) 引入的三方库都有完整的tar.gz文件可以下载，但是微软的fourq仓库只有git仓，这该怎么引入？

github 所有的 commit 都可以变成一个 tar.gz 的包，fourq 就用
https://github.com/microsoft/FourQlib/archive/{commit}.tar.gz

**Comment by Candicepan** [comment]
> 【Tonytan123 Give it to me】

感谢您的认领。经沟通，该任务先进行回收，欢迎认领更适合您的任务呀～

**Comment by cfbreathing** [comment]
【cfbreathing Give it to me】

**Comment by muyixi315** [comment]
`bazel run -c opt //yacl/crypto/ecc/benchmark:benchmark -- --curve=ed25519
`![image](https://github.com/secretflow/yacl/assets/17821682/231c5970-ec94-4412-827d-b09832bb7706)

**Comment by Yeekin-GYJ** [comment]
hi [muyixi315](https://github.com/muyixi315)，改项目已由[cfbreathing](https://github.com/cfbreathing)认领进行任务开发，可以看下其他OSCP的任务哦，欢迎认领呀！认领前记得填写OSCP报名表，感谢对隐语的关注～ 如有疑问欢迎添加小助手微信:SecretFlow04

**Comment by Candicepan** [comment]
> 【cfbreathing Give it to me】

感谢你对隐语开源的支持呀～该功能已由隐语内部已经实现，预计在下个版本中发布实现后的功能。欢迎认领其他感兴趣的任务呀～
