### ISSUE TITLE
A question about pull #163

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#165]
In a recent [update](https://github.com/secretflow/yacl/pull/163), you added `using ValueType = T;` in arg_k.h and changed  `T GetRequired(const SpiArgKey<T> &key) const {` in arg_set.h to 
```
auto GetRequired(const SpiArgKey<T> &key) const ->
typename SpiArgKey<T>::ValueType {
```
I can not see any problems of the original codes. What’s the advantage of this update?

**Comment by usafchn** [comment]
@maths644311798  Thank you for your concern. I think that both ways of writing are equivalent, and there is no special intention behind the change here. It is an unintentional change.
