### ISSUE TITLE
The relation between ic_factory and interconnection

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#194]
Secretflow has a library named "interconnection". In Yacl, there is a sentence `REGISTER_DRBG_LIBRARY("Interconnection", 100, IcDrbg::Check, IcDrbg::Create);` in a file named "ic_factory.h". What is the relation between ic_factory and interconnection?

**Comment by Jamie-Cui** [comment]
It's a part of Yacl's Tweak on DRBG to support the Interconnection standard between different framework vendors. TLDR: This feature (ic_drbg) is only experimental and is not recommended to use.

If you are interested, you'll notice that this is an implementation of hash drbg that complies NIST standard, the reason for that is OpenSSL3 has hidden some of its drbg implementation details, and we want to make some modifications to its implementation.

**Comment by usafchn** [comment]
The `Secretflow/Interconnection` repo stores documents, standards, and interfaces for interconnection (Chinese: 隐私计算平台互联互通).

`REGISTER_DRBG_LIBRARY("Interconnection", 100, IcDrbg::Check, IcDrbg::Create)` implements DRBG that meets interconnection standards
