### ISSUE TITLE
A small problem in gadget

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#262]
In  yacl/math/gadget.h,  `inline uint64_t Log2Ceil(uint64_t x)`. Is the sentence `return x == 1 ? 1 : Log2Floor(x - 1) + 1;` right? When x=1, it should be Log2(1)=0. I know that if we only need 0 bit memory, we can reserve 1 bit memory. But `Log2Ceil` being not accurate may cause some problems.

**Comment by Jamie-Cui** [comment]
bool to int conversion is implicit.

§4.7/4 from the C++ 11 or 14 Standard, §7.8/4 from the C++ 17 Standard, §7.3.9/2 from the 20 Standard says (Integral Conversion)

> If the source type is bool, the value false is converted to zero and the value true is converted to one.

ref: 
1. https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4713.pdf, 
2. https://stackoverflow.com/a/5369783/9369290

**Comment by maths644311798** [comment]
@Jamie-Cui, what is the relation between `Log2Ceil(uint64_t x)` and implicit conversion from bool to int?

**Comment by Jamie-Cui** [comment]
Sorry my mistake. It seems a bug to me. @liang-xiaojian Can you confirm is this a bug?

**Comment by Jamie-Cui** [comment]
hi @maths644311798 can you create a PR for this?
