### ISSUE TITLE
WSL-Ubuntu20.04编译Yacl（bazel build //... -c dbg）报错：

### ISSUE THREAD

**Issue by ZeroAntelope** [secretflow/yacl#293]
ERROR: /home/ping/yacl/yacl/link/BUILD.bazel:134:14: Generating Descriptor Set proto_library //yacl/link:link_proto failed: (Exit 1): process-wrapper failed: error executing command
  (cd /home/ping/.cache/bazel/_bazel_ping/47889ea07e4c9866ea53fcfa17e9ecf0/sandbox/processwrapper-sandbox/749/execroot/yacl && \
  exec env - \
    PATH='/home/ping/.local/bin:/home/ping/bin:/home/wjl/work/gcc112/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu20.04LTS_2004.6.16.0_x64__79rhkp1fndgsc:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Users/admin/AppData/Local/Programs/Python/Python311/Scripts:/mnt/c/Users/admin/AppData/Local/Programs/Python/Python311:/mnt/c/Users/admin/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/JetBrains/PyCharm Community Edition 2021.1.1/bin:/mnt/d/LxRunOffine-v3.5.0-mingw:/mnt/c/Users/admin/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/msys64/mingw64/bin:/snap/bin:/home/ping/bin:/usr/local/go/bin:/home/ping/go/bin' \
    TMPDIR=/tmp \
  /home/ping/.cache/bazel/_bazel_ping/install/20da5ab742b8d3d499c34fdafcd3c8b8/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/home/ping/.cache/bazel/_bazel_ping/47889ea07e4c9866ea53fcfa17e9ecf0/sandbox/processwrapper-sandbox/749/stats.out' bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc --direct_dependencies yacl/link/link.proto '--direct_dependencies_violation_msg=%s is imported, but //yacl/link:link_proto doesn'\''t directly depend on a proto_library that '\''srcs'\'' it.' '--descriptor_set_out=bazel-out/k8-dbg/bin/yacl/link/link_proto-descriptor-set.proto.bin' '-Iyacl/link/link.proto=yacl/link/link.proto' yacl/link/link.proto)
bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc)

**Comment by Chrisdehe** [comment]
从报错来看，是你的C++库版本较低不兼容，按照报错内容升级你的libstdc++
同时其他依赖也可以参考[此文档](https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#linux)
