### ISSUE TITLE
A problem in yacl/kernels/svole_kernel.cc

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#298]
In yacl/kernels/svole_kernel.cc, there is a function
```
void SVoleKernel::eval_multithread(const std::shared_ptr<link::Context>& lctx, uint128_t* out_delta,
absl::Span<uint128_t> out_c, int threads)
{…}
```
It seems that `*out_delta = std::get<SilentVoleSender>(tl_core).GetDelta();` is independent of the division of tasks. So this sentence can be moved outside the tasks.

**Comment by liang-xiaojian** [comment]
Good idea.
It seems that we could set `*out_delta = std::get<SilentVoleSender>(core_).GetDelta();` before submitting the tasks.
