### ISSUE TITLE
Problem in yacl/crypto/ossl-provider/helper.h

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#299]
In yacl/crypto/ossl-provider/helper.h, the path returned by `std::string GetProviderPath()` should contain “execroot” and “bin”. But after bazel building, I do not find such paths. 
Do they really exist? If they do not exist, how do the functions relying on `std::string GetProviderPath()` work?

**Comment by liang-xiaojian** [comment]
Sure, the paths do exist. The output directory layout could be found in [this link](https://bazel.build/versions/6.3.0/remote/output-directories).
Additionally, `bazel-*` is a link. (You could view the original files by using `ls -lrt`)

**Comment by maths644311798** [comment]
OK, I see the execroot paths in `~/.cache/bazel/_bazel_root/...`
