### ISSUE TITLE
Windows x86_64 platform support

### ISSUE THREAD

**Issue by imwangyt** [secretflow/yacl#305]
请问，yacl不支持Windows x86_64 platform，是用到了Windows platform上目前没有提供的library么？具体是哪一些？

**Comment by anakinxc** [comment]
> 请问，yacl不支持Windows x86_64 platform，是用到了Windows platform上目前没有提供的library么？具体是哪一些？

brpc 就不支持 Windows https://github.com/apache/brpc/issues/2109
而且在 Windows 上大部分功能可以通过 WSL/Docker 来实现，所以短时间内也应该不会有支持 Windows 的计划
当然社区如果有人贡献 Windows 支持，也是欢迎的

**Comment by imwangyt** [comment]
> > 请问，yacl不支持Windows x86_64 platform，是用到了Windows platform上目前没有提供的library么？具体是哪一些？
> 
> brpc 就不支持 Windows [apache/brpc#2109](https://github.com/apache/brpc/issues/2109) 而且在 Windows 上大部分功能可以通过 WSL/Docker 来实现，所以短时间内也应该不会有支持 Windows 的计划 当然社区如果有人贡献 Windows 支持，也是欢迎的

感谢答复。
让C端用户使用WSL/Docker，难度有点大。
