### ISSUE TITLE
关于yacl编译后的安装问题。

### ISSUE THREAD

**Issue by ShallMate** [secretflow/yacl#342]
我按文档中说的方法成功build了yacl（build的命令用的：bazel build --linkopt=-ldl //... -c opt）。但是我没有找到install到本地的方法。当然不用install也能使用，但是由于我以前没有用过bazel，我不知道如何在vscode中配置bazel编译的project。现在我的vscode打开已经编译好的yacl仍然会有提示错误，所以我想解决这个问题。要么是能install到本地，要么是能否告诉我在vscode中配置yacl的方法？

ps. 
我使用bazel test  //...发现大概40多个test不能通过测试。然后我将test命令又改为了：bazel test --linkopt=-ldl //...
这样只有1个test没有通过测试。具体是
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] BrpcLinkSSLTest.OneWaySSL
[  FAILED  ] BrpcLinkSSLTest.TwoWaySSL
这应该不会影响我后续的使用吧？

**Comment by oceanqdu** [comment]
@ShallMate 请问一下，你解决这个问题了吗？怎么install到本地的

**Comment by ShallMate** [comment]
@oceanqdu 这个不影响你后续的使用。YACL现在应该是install到本地当成系统库去用的。您可以在examples那样去使用YACL。

**Comment by ShallMate** [comment]
@oceanqdu 关于VSCODE，文档里面有脚本，运行一下就好了

**Comment by ShallMate** [comment]
![image](https://github.com/user-attachments/assets/7c25a387-1815-483a-93a3-3ed3004994f2)
@oceanqdu

**Comment by oceanqdu** [comment]
@ShallMate 感谢您的回答，我现在的场景是我希望在另一个项目中使用yacl，另一个项目中不是通过bazel编译的，而是使用makefile来进行编译的，这种情况下请问您知道应该怎么来用yacl吗？

**Comment by ShallMate** [comment]
您可以让那个项目安装到本地，然后用yacl的bazel来编译，这是可行的。如果这样做不符合您的预期，其他的方法的话您可以单独开一个issue问一下YACL的开发者试试看有没有更好的解决方案。
