### ISSUE TITLE
关于yacl的使用

### ISSUE THREAD

**Issue by oceanqdu** [secretflow/yacl#450]
由于之前没用过bazel编译，不太了解如何使用编译好的yacl，现在根据文档已经使用bazel build编译好了yacl，现在我的需求场景是：我希望在已有的使用makeflie编译的项目中来使用yacl，我该怎么做？需要手动把所有的.so文件和所有的include头文件手动移动过去吗？

**Comment by lanyy9527** [comment]
如果自己的项目不是bazel的话，建议先看下yacl xc/cmake分支的 cmakelist 尝试一下（已线下回复）
