### ISSUE TITLE
The function log10 is strange

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#66]
In yacl/base/int128.h, there is a strange sentence:
  constexpr double log10(uint128_t x) { return 0.0; }
Why is it always 0? Or is it a bug?

**Comment by anakinxc** [comment]
Hi @maths644311798 

This is just a hack to make some legacy thingy happy.
And it is no longer required, I'll delete this piece of code later.

Thanks for reporting :D

**Comment by maths644311798** [comment]
@anakinxc 
In yacl/base/int128.h, there is still a strange thing. It has been a long time that gcc supports abs(__int128_t). But the following code 

constexpr int128_t abs(int128_t x)

is in yacl/base/int128.h.

**Comment by anakinxc** [comment]
> @anakinxc In yacl/base/int128.h, there is still a strange thing. It has been a long time that gcc supports abs(__int128_t). But the following code
> 
> constexpr int128_t abs(int128_t x)
> 
> is in yacl/base/int128.h.

As far as I can remember, this is due to missing constexpr
