### ISSUE TITLE
An optimization in segment_tree.h

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#68]
In yacl/utils/segment_tree.h, SegmentTree<T>::GetSegments() gets a copy of its data member segments_. I think you can just use the copy constructor to implement the function instead of a for loop. For example,

std::vector<std::pair<T, T>> GetSegments() const {
    std::vector<std::pair<T, T>> ret(segments_);
    return ret;
  }

Are there any reasons to use a for loop in SegmentTree<T>::GetSegments()?

**Comment by Chrisdehe** [comment]
hi,@maths644311798 
Confirm,whether this issue is closed?
Thank!
