### ISSUE TITLE
go 想使用这个库需要安装什么嘛

### ISSUE THREAD

**Issue by clearlove520** [secretflow/yacl#70]
go 想使用这个库需要安装什么嘛

**Comment by anakinxc** [comment]
yacl 是一个 c++ 写的库，在 go 里使用需要自己做 [go c++ binding](https://medium.com/mysterium-network/golang-c-interoperability-caf0ba9f7bf3)

**Comment by clearlove520** [comment]
go c++ binding 是我要直接在代码上直接引入 还是对bazel 编译完成的程序做go bind

**Comment by anakinxc** [comment]
> go c++ binding 是我要直接在代码上直接引入 还是对bazel 编译完成的程序做go bind

应该是需要在代码里添加 go binding 相关的内容

**Comment by clearlove520** [comment]
我使用cgo作了go bind 但发现因为是通过babel进行管理依赖库的，所以导库好像很难，不知道是不是我的做法有误。

**Comment by anakinxc** [comment]
> 我使用cgo作了go bind 但发现因为是通过babel进行管理依赖库的，所以导库好像很难，不知道是不是我的做法有误。

导库很难是指的什么

**Comment by clearlove520** [comment]
就是得一个一个手动导入外部依赖

**Comment by anakinxc** [comment]
> 就是得一个一个手动导入外部依赖

emmmm，你可以看一下[这里](https://github.com/bazelbuild/rules_go)有没有什么有用的东西
