### ISSUE TITLE
TempFile in LeveldbKVStore

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#71]
In yacl/io/kv/leveldb_kvstore.cc, there is a constructor as the following:
//
LeveldbKVStore::LeveldbKVStore(bool is_temp, const std::string &file_path)
    : is_temp_(is_temp) {
  leveldb::Options options;
  options.create_if_missing = true;

  std::string db_path = file_path;
  if (db_path.empty()) {
    butil::TempFile temp_file;
    db_path = std::string(temp_file.fname());
  }

  leveldb::DB *db_ptr = nullptr;
  leveldb::Status db_status = leveldb::DB::Open(options, db_path, &db_ptr);
  YACL_ENFORCE(db_status.ok(), "leveldb open failed, msg: {}",
               db_status.ToString());
  db_.reset(db_ptr);
  path_ = db_path;
  is_open_ = true;
}
//

If file_path is empty, then temp_file creates a temporary file. Then its destructor unlinks the temporary file, causing the deletion of the file. Then leveldb::DB::Open can not succeed. What is the role that temp_file plays?

**Comment by maths644311798** [comment]
Here is an example that explains the short life of temp_file and its associated file.
//
#include <iostream>
#include <map>
#include <string>
#include "butil/files/temp_file.h"
#include <unistd.h>

using namespace std;
 
int main()
{
  {
    butil::TempFile temp_file;
    system("ls");
    sleep(10);
  }
  system("ls");
   return 0;
}
//
its output is the following two lines:
hello temp_file_EeyS2T
hello

**Comment by anakinxc** [comment]
@zhanglei486 Can you take a look?

**Comment by zhanglei486** [comment]
when fileuse_path is null, use butils::TempFile get temp file name，real temp file create by leveldb.

**Comment by maths644311798** [comment]
> when fileuse_path is null, use butils::TempFile get temp file name，real temp file create by leveldb.

Well. It seems a waste of resource to useuse butils::TempFile to get temp file name. There are many quicker ways to obtaining a temp file name. For example, butil just fixes a macro as a temp file name.
After all, we don't have to invoke the constructor and destructor of butils::TempFile just for a name.

**Comment by anakinxc** [comment]
std::tmpnam is a potential replacement

**Comment by maths644311798** [comment]
std::tmpnam is not safe. mkstemp is a good choice. The following code is extracted from butil::TempFile. But we don't need to construct butil::TempFile.

  char temp_file[]="yacl_tmpfile_XXXXXX";
  close(mkstemp(temp_file));
  unlink(temp_file);
  db_path = temp_file;

**Comment by anakinxc** [comment]
> std::tmpnam is not safe. mkstemp is a good choice. The following code is extracted from butil::TempFile. But we don't need to construct butil::TempFile.
> 
> char temp_file[]="yacl_tmpfile_XXXXXX"; close(mkstemp(temp_file)); unlink(temp_file); db_path = temp_file;

mkstemp is kind of a platform specific API, there might be behavior differences on Linux and macOS. 

Also it will be a problem if we want to support Windows at some point.

Performance-wise create a folder and unlink it is way more expensive than construct and destruct an object.

Fairly speaking current behavior is not safe anyway😅Between butil releases the created tempfile and leveldb reuses that name, no one can guarantee that name is still unused

**Comment by maths644311798** [comment]
The constructor of butil::TempFile already invokes mkstemp(). So the current version relies on mkstemp().

**Comment by anakinxc** [comment]
> The constructor of butil::TempFile already invokes mkstemp(). So the current version relies on mkstemp().

Yes, but that's not in our codebase, so we don't need to maintain that.

The point is if we still have to call mkstemp, why not just using butil::TempFile?  

If performance is the reason to drop butil::TempFile, new solution should try it's best to avoid create tempfile at the first place.

**Comment by Jamie-Cui** [comment]
Hi 如果没有进一步的问题，这个 issue 先 close 掉了，如果有后续问题可以 re-open this issue，thx
