### ISSUE TITLE
Bugs in yacl/kv/io/

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#72]
Here is a problem in yacl/kv/io/. In LeveldbKVStore::~LeveldbKVStore(), observe the sentence
  SPDLOG_INFO("Delete tmp file:{} exception {}", path_, e.what());
When there are more than one parameters, SPDLOG_INFO does not accept const char*.

And in LeveldbKVStore::Get, the sentence
SPDLOG_ERROR("Get key: {}, error:", key, db_status.ToString());
misses a "{}"

**Comment by anakinxc** [comment]
Hi @maths644311798 

Would you like to submit a pull request to fix these issues?

Thanks

**Comment by anakinxc** [comment]
> I have pulled a request. But this is the first time to do that. So if there are any problems, please tell me.

Thanks, I have linked the pull request to this issue

**Comment by maths644311798** [comment]
I have tested the code today. This problem is not solved. In leveldb_kvstore.cc, the following sentence can not be compiled,

  SPDLOG_INFO("Delete tmp file:{} exception {}", path_, std::string(e.what()));

reason: std::string(e.what()) is a right value. But  SPDLOG_INFO needs a left value. This is strange.

One solution is 
    std::string e_tmp = e.what();
    SPDLOG_INFO("Delete tmp file:{} exception {}", path_, e_tmp);

**Comment by anakinxc** [comment]
> I have tested the code today. This problem is not solved. In leveldb_kvstore.cc, the following sentence can not be compiled,
> 
> SPDLOG_INFO("Delete tmp file:{} exception {}", path_, std::string(e.what()));
> 
> reason: std::string(e.what()) is a right value. But SPDLOG_INFO needs a left value. This is strange.
> 
> One solution is std::string e_tmp = e.what(); SPDLOG_INFO("Delete tmp file:{} exception {}", path_, e_tmp);

Plz double check your toolchain version. CI has successfully built the code.

**Comment by maths644311798** [comment]
I figure out some reasons. The order of headers influence the functions of spdlog.

#include "fmt/format.h"
#include "spdlog/spdlog.h"

Under this order, the sentence
  SPDLOG_INFO("Delete tmp file:{} exception {}", s, std::string(e.what()));
can not be compiled.

#include "spdlog/spdlog.h"
#include "fmt/format.h"

This order works well. This may be related to my context. I am looking for the essence of the problem.
