### ISSUE TITLE
c++20 compilation error

### ISSUE THREAD

**Issue by 982945902** [secretflow/yacl#82]
`
In file included from external/com_github_fmtlib_fmt/include/fmt/format.h:48,
                 from external/com_github_fmtlib_fmt/include/fmt/ostream.h:20,
                 from external/yacl/yacl/crypto/base/mpint/mp_int.h:21,
                 from external/yacl/yacl/crypto/base/ecc/ec_point.h:20,
                 from external/yacl/yacl/crypto/base/ecc/ec_point.cc:15:
external/com_github_fmtlib_fmt/include/fmt/core.h: In instantiation of 'constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_value(T&&) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; T = const yacl::crypto::MPInt&]':
external/com_github_fmtlib_fmt/include/fmt/core.h:1777:29:   required from 'constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; fmt::v9::detail::type <anonymous> = fmt::v9::detail::type::custom_type; T = const yacl::crypto::MPInt&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]'
external/com_github_fmtlib_fmt/include/fmt/core.h:1901:77:   required from 'constexpr fmt::v9::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {const yacl::crypto::MPInt&, const yacl::crypto::MPInt&}; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {yacl::crypto::MPInt, yacl::crypto::MPInt}]'
external/com_github_fmtlib_fmt/include/fmt/core.h:1918:31:   required from 'constexpr fmt::v9::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<Args>::type>::type ...> fmt::v9::make_format_args(Args&& ...) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {const yacl::crypto::MPInt&, const yacl::crypto::MPInt&}]'
external/com_github_fmtlib_fmt/include/fmt/core.h:3206:44:   required from 'std::string fmt::v9::format(fmt::v9::format_string<T ...>, T&& ...) [with T = {const yacl::crypto::MPInt&, const yacl::crypto::MPInt&}; std::string = std::__cxx11::basic_string<char>; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, const yacl::crypto::MPInt&, const yacl::crypto::MPInt&>]'
external/yacl/yacl/crypto/base/ecc/ec_point.cc:28:21:   required from here
external/com_github_fmtlib_fmt/include/fmt/core.h:1757:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
`

gcc version 11.3.0
-std=gnu++20

why not define `namespace fmt { struct formatter<...>: ostream_formatter {};}`

**Comment by anakinxc** [comment]
> `In file included from external/com_github_fmtlib_fmt/include/fmt/format.h:48, from external/com_github_fmtlib_fmt/include/fmt/ostream.h:20, from external/yacl/yacl/crypto/base/mpint/mp_int.h:21, from external/yacl/yacl/crypto/base/ecc/ec_point.h:20, from external/yacl/yacl/crypto/base/ecc/ec_point.cc:15: external/com_github_fmtlib_fmt/include/fmt/core.h: In instantiation of 'constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_value(T&&) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; T = const yacl::crypto::MPInt&]': external/com_github_fmtlib_fmt/include/fmt/core.h:1777:29: required from 'constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; fmt::v9::detail::type <anonymous> = fmt::v9::detail::type::custom_type; T = const yacl::crypto::MPInt&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]' external/com_github_fmtlib_fmt/include/fmt/core.h:1901:77: required from 'constexpr fmt::v9::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {const yacl::crypto::MPInt&, const yacl::crypto::MPInt&}; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {yacl::crypto::MPInt, yacl::crypto::MPInt}]' external/com_github_fmtlib_fmt/include/fmt/core.h:1918:31: required from 'constexpr fmt::v9::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<Args>::type>::type ...> fmt::v9::make_format_args(Args&& ...) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {const yacl::crypto::MPInt&, const yacl::crypto::MPInt&}]' external/com_github_fmtlib_fmt/include/fmt/core.h:3206:44: required from 'std::string fmt::v9::format(fmt::v9::format_string<T ...>, T&& ...) [with T = {const yacl::crypto::MPInt&, const yacl::crypto::MPInt&}; std::string = std::__cxx11::basic_string<char>; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, const yacl::crypto::MPInt&, const yacl::crypto::MPInt&>]' external/yacl/yacl/crypto/base/ecc/ec_point.cc:28:21: required from here external/com_github_fmtlib_fmt/include/fmt/core.h:1757:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt`
> 
> gcc version 11.3.0 -std=gnu++20
> 
> why not define `namespace fmt { struct formatter<...>: ostream_formatter {};}`

is there any reason to build with -std=gnu++20?

**Comment by 982945902** [comment]
to compile c++20, fork https://github.com/982945902/yacl

**Comment by anakinxc** [comment]
I see.

Consider status of compiler support, especially library part, we may not move to c++20 anytime soon.

But PRs to improve compliance are welcome. :P
