### ISSUE TITLE
Problems in yacl/io/rw

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#85]
In the 91 line of csv_writer.cc:
	  YACL_THROW("unknow Schema::type {}", types[c]);
Note that types[c] is a variable of enum type. So it does not fit into the parameters of fmt. 
I think int(types[c]) will be better.  Similar problems occur in csv_reader.cc.

**Comment by anakinxc** [comment]
> csv_writer.cc:

Hi @maths644311798 

Yes, static_cast<int>(types[c]) is definitely safer. But since it's unscoped enum, it should be able to implicit convert to int.

A PR to make it looks better is welcome :P

Cheers

**Comment by maths644311798** [comment]
@anakinxc I have pulled a request adding type conversion. Please review it.
