### ISSUE TITLE
Problems in yacl/link/transport

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#90]
(1) You claim that the transport protocol is based on gRPC in www.secretflow.org.cn. But the code shows that it is based on bRPC. Why?

(2) Another problem is the function
`
explicit ChannelBrpc(size_t self_rank, size_t peer_rank, Options options,
                       bool exit_if_async_error = true)
      : ChannelBase(self_rank, peer_rank, exit_if_async_error),
        options_(std::move(options)) {}

  explicit ChannelBrpc(size_t self_rank, size_t peer_rank,
                       size_t recv_timeout_ms, Options options,
                       bool exit_if_async_error = true)
      : ChannelBase(self_rank, peer_rank, recv_timeout_ms, exit_if_async_error),
        options_(std::move(options)) {}
`
But ChannelBase does not have such interface.

**Comment by 6fj** [comment]
@usafchn could you please have a look?

**Comment by shaojian-ant** [comment]
(1) Brpc is compatible whith grpc if set the appropriate configuration, refer to https://github.com/apache/brpc/blob/master/docs/en/http_derivatives.md#h2grpc

(2) I don't fully understand your question. ChannelBrpc is a class inherited from ChannelBase, and it has some parameters in its construstors propagated to ChannelBase except the options parameters.

**Comment by maths644311798** [comment]
Thanks. For the problem (2), I see that my copy of codes is not updated completely.

**Comment by maths644311798** [comment]
I want to ask one moe question. 
(3) What is the main advantage to design such a transport protocol instead of using TCP directly?

**Comment by shaojian-ant** [comment]
The word transport in our code does not mean the transport in the internet protocol stack. It use grpc/brpc to transport our data, so it is on application layer. By using grpc/brpc service framework,  we need not consider a lot about sending/receiving messages, and it simplifies work on definition of our own application layer protocol,  I think this is the main advantage.

**Comment by anakinxc** [comment]
> I want to ask one moe question.
> (3) What is the main advantage to design such a transport protocol instead of using TCP directly?

Well, good question, this is more or less a practical thingy.

In thoery, one can always use socket directly. But in real world scenarios, due to complexity of network, using RPC is just a simpler and safer option with reasonable overhead for most cases.
