### ISSUE TITLE
Problems in yacl/link/context

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#94]
(1)	In yacl/link/context,
	should Context.stats_ be a const std::shared_ptr?
	
(2)	In 

void SendAsync(size_t dst_rank, ByteContainerView value, std::string_view tag); 

what does tag mean? It is not defined in secretflow’s interconnection protocol.
	
(3)	If every party holds one context, then the following code implies that everyone should maintain the counter of every p2p-channel.
	
	Context::Context(…)
	…
	for (size_t src = 0; src < world_size; ++src) {
	    for (size_t dst = 0; dst < world_size; ++dst) {
	      p2p_counter_[std::make_pair(src, dst)] = 0U;
	    }
	  }

**Comment by anakinxc** [comment]
1) I don't think there is any benefits to use const std::shared_ptr

2) tag holds debug information use by link tracer

3) Yes, that's what happens in NextP2PId

**Comment by maths644311798** [comment]
There is still a little problem in (3). context.cc always use

NextP2PId(rank_,...)

or 

NextP2PId(..., rank_)

I don't see the necessity for every party to maintain every p2p_counter_.
Maybe one party only need to maintain the p2p_counter_ of channels where he is the sender or receiver.

**Comment by maths644311798** [comment]
I have more questions.
(4) Does the p2p_counter_ of some channel coincide with the seq_id of the channel?
	
(5) In Context::Context(…)

    ...
	  channels_(std::move(channels)),
	      receiver_loop_(std::move(msg_loop))
   ...

	Then in Context::Spawn()

	 …
	auto sub_ctx =
	      std::make_unique<Context>(sub_desc, rank_, channels_, receiver_loop_);
	…
	
	Does it mean that the sub-context robs the this->channels_ and this-> receiver_loop_? When do we need to spawn a context? 
	
(6)	When do we need to invoke Context::SubWorld?

**Comment by warriorpaw** [comment]
3. Context is used in the MPC protocol. The execution process of the MPC protocol must be completely symmetrical, and Send and Recv need to be 1-to-1 correspondence.

4. Channel is shared by all Contexts, and all p2p_counter_ of each Context is starts from 0, there is no correspondence between p2p_counter_ and seq_id.

5. The constructor of Context is ``` std::vector<std::shared_ptr<transport::IChannel>> channels ``` , it will copy channels instead of directly move the original channels_.

6. SubWorld is used when the MPC protocol is switched, such as switching from 3PC-SPDZ to 2PC-SPDZ.

**Comment by maths644311798** [comment]
(3) (5) are not solved. 
(3) Assume there are three parties whose ranks are 0, 1, 2 respectively. Why party 0 maintains the p2p_counter_ [1,2]?
(5) It seems that three variables are moved.

      desc_(std::move(desc)),
      ...
      channels_(std::move(channels)),
      receiver_loop_(std::move(msg_loop))

 When do we need to spawn a context?

**Comment by warriorpaw** [comment]
3. There are unnecessary variables in p2p_counter_, but this does not cause any problems


5. The constructor of Context is
```
Context::Context(ContextDesc desc, size_t rank,
                std::vector<std::shared_ptr<transport::IChannel>> channels, // copy channels_ to channels
                std::shared_ptr<transport::IReceiverLoop> msg_loop,
                bool is_sub_world)
    : desc_(std::move(desc)),
      rank_(rank),
      channels_(std::move(channels)),                                        // then move channels to this->channels_
      receiver_loop_(std::move(msg_loop)),
      recv_timeout_ms_(desc_.recv_timeout_ms),
      is_sub_world_(is_sub_world)
```


``` When do we need to spawn a context? ```
Please read the comments for Context:
https://github.com/secretflow/yacl/blob/main/yacl/link/context.h#L147


> (3) (5) are not solved. (3) Assume there are three parties whose ranks are 0, 1, 2 respectively. Why party 0 maintains the p2p_counter_ [1,2]? (5) It seems that three variables are moved.
> 
> ```
>   desc_(std::move(desc)),
>   ...
>   channels_(std::move(channels)),
>   receiver_loop_(std::move(msg_loop))
> ```
> 
> When do we need to spawn a context?

**Comment by maths644311798** [comment]
Context::Context(…)
…
for (size_t src = 0; src < world_size; ++src) {
    for (size_t dst = 0; dst < world_size; ++dst) {
      p2p_counter_[std::make_pair(src, dst)] = 0U;
    }
  }

This does cause some waste of space when the number of parties is big, almost O(world_size^2) space.

**Comment by anakinxc** [comment]
> Context::Context(…) … for (size_t src = 0; src < world_size; ++src) { for (size_t dst = 0; dst < world_size; ++dst) { p2p_counter_[std::make_pair(src, dst)] = 0U; } }
> 
> This does cause some waste of space when the number of parties is big, almost O(world_size^2) space.

number of parties usually won't be that large. usually at most 4.

Other things will get worse much faster than this...

**Comment by maths644311798** [comment]
One More question: (7) In the Scatter protocol defined in https://www.secretflow.org.cn/docs/interconnection/latest/zh-Hans/protocols/transport#scatter, the global counter begins at 0. That is, the key begins like "root:0:SCATTER".
But in the code

std::string Context::NextId() {
  return fmt::format("{}:{}", desc_.id, ++counter_);
}

It seems that the first key looks like "root:1:SCATTER" instead of "root:0:SCATTER".

**Comment by maths644311798** [comment]
One More question: (7) In the Scatter protocol defined in https://www.secretflow.org.cn/docs/interconnection/latest/zh-Hans/protocols/transport#scatter, the global counter begins at 0. That is, the key begins like "root:0:SCATTER".
But in the code
std::string Context::NextId() {
return fmt::format("{}:{}", desc_.id, ++counter_);
}
It seems that the first key looks like "root:1:SCATTER" instead of "root:0:SCATTER". This is just a consistency problem. @warriorpaw

**Comment by warriorpaw** [comment]
> One More question: (7) In the Scatter protocol defined in https://www.secretflow.org.cn/docs/interconnection/latest/zh-Hans/protocols/transport#scatter, the global counter begins at 0. That is, the key begins like "root:0:SCATTER". But in the code std::string Context::NextId() { return fmt::format("{}:{}", desc_.id, ++counter_); } It seems that the first key looks like "root:1:SCATTER" instead of "root:0:SCATTER". This is just a consistency problem. @warriorpaw

This is a mistake in the document, can you submit a PR to fix it.

**Comment by maths644311798** [comment]
Sorry, I don't know how to change the document in https://www.secretflow.org.cn/docs/interconnection/latest/zh-Hans/protocols/transport#scatter.

**Comment by warriorpaw** [comment]
> Sorry, I don't know how to change the document in https://www.secretflow.org.cn/docs/interconnection/latest/zh-Hans/protocols/transport#scatter.

Here is the code
https://github.com/secretflow/interconnection/blob/main/docs/protocols/transport.rst
