### ISSUE TITLE
在 YACL 上支持新的 Codes: LDPC Codes

### ISSUE THREAD

**Issue by Candicepan** [secretflow/yacl#96]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第三期](https://github.com/orgs/secretflow/discussions/1007)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx#)进行哈～

## 任务介绍
- 任务名称：在 YACL 上支持新的 Codes: LDPC Codes
- 技术方向：YACL，密码学，编码理论
- 任务难度：进阶🌟🌟

## 详细要求
由于目前 Silent-Extension 的 OTe 算法基于不同的 LPN 问题假设，目前 YACL 已实现基于 Primal LPN 的算法，因此需要探索、支持基于其他假设（例如 dual LPM）的算法，支持 LDPC Code 是实现该类算法的前置工作。
- 安全性
  - 遵循论文中的协议实现
  - if possible，默认安全强度为 128 bit
- 功能性：
  - 支持 Encode 函数
  - 支持相应参数调整
-  代码规范：
  - C++ 代码需要遵循 Google C++ style guidelines，除了以下几条 exceptions
    - Exceptions are allowed and encouraged where appropriate.
    - Header guards should use #pragma once.
    - Adopt camelBack for function names.
    - Use fixed width integer types whenever possible.
    - Avoid using size_t on interface APIs.
  - 可使用 clangd 进行代码格式化
  - 可使用 cpplint 检查格式
- 提交说明：关联该 issue 并提交代码至 https://github.com/secretflow/yacl/tree/main/yacl/crypto/tools

## 能力要求
- 熟悉密码学或者编码理论
- 熟悉 C++ 以及性能优化

## 操作说明
- 参考内容：
  - [原始论文](https://hal.science/hal-03374192/document)
  - [其他代码库实现](https://github.com/osu-crypto/libOTe/tree/master/libOTe/Tools/EACode)
  - [接口](https://github.com/osu-crypto/libOTe/tree/master/libOTe/Tools/LDPC)
- 示例：[d-Local Linear Code](https://github.com/secretflow/yacl/blob/main/yacl/crypto/tools/linear_code.h#L70)

**Comment by Candicepan** [comment]
该功能已由隐语团队实现，将在下一个版本发布～该任务将直接关闭～具体实现在下个版本发布后将在该 issue 中同步给大家哈～（另外，新版本发布后也将发布新的 YACL 任务哟～敬请期待

**Comment by Jamie-Cui** [comment]
该实现已经发布～
